spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/article_comments
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/article_comments
    user: postgres
    password: postgres
server:
  port: 8081